name: Update mirror
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-mirror:
    name: Update mirror
    runs-on: ubuntu-latest
    steps:
      - name: Update mirror
        run: |
          git clone --mirror https://git.sr.ht/~lnikkila/nginx-webdav-quirks .
          git push --mirror "https://x:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
